export interface StockDef {
  symbol: string;
  name: string;
  exchange: 'NASDAQ' | 'NYSE' | 'TSX';
  currency: 'USD' | 'CAD';
  sector?: string;
}

export const STOCKS: StockDef[] = [
  // ── US NASDAQ ────────────────────────────────────────────
  { symbol: 'AAPL',  name: 'Apple Inc.',               exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'MSFT',  name: 'Microsoft Corporation',    exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.',             exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'AMZN',  name: 'Amazon.com Inc.',           exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'NVDA',  name: 'NVIDIA Corporation',        exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'META',  name: 'Meta Platforms Inc.',       exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'TSLA',  name: 'Tesla Inc.',                exchange: 'NASDAQ', currency: 'USD', sector: 'Auto' },
  { symbol: 'AVGO',  name: 'Broadcom Inc.',             exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'COST',  name: 'Costco Wholesale',          exchange: 'NASDAQ', currency: 'USD', sector: 'Retail' },
  { symbol: 'NFLX',  name: 'Netflix Inc.',              exchange: 'NASDAQ', currency: 'USD', sector: 'Media' },
  { symbol: 'AMD',   name: 'Advanced Micro Devices',   exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'QCOM',  name: 'Qualcomm Inc.',             exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'INTC',  name: 'Intel Corporation',         exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'CSCO',  name: 'Cisco Systems Inc.',        exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'ADBE',  name: 'Adobe Inc.',                exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'TXN',   name: 'Texas Instruments',         exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'AMAT',  name: 'Applied Materials',         exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'MU',    name: 'Micron Technology',         exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'SBUX',  name: 'Starbucks Corporation',     exchange: 'NASDAQ', currency: 'USD', sector: 'Food' },
  { symbol: 'PYPL',  name: 'PayPal Holdings',           exchange: 'NASDAQ', currency: 'USD', sector: 'Finance' },
  { symbol: 'PANW',  name: 'Palo Alto Networks',        exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'CRWD',  name: 'CrowdStrike Holdings',      exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'MRVL',  name: 'Marvell Technology',        exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'ASML',  name: 'ASML Holding NV',           exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  { symbol: 'LRCX',  name: 'Lam Research',              exchange: 'NASDAQ', currency: 'USD', sector: 'Tech' },
  // ── US NYSE ──────────────────────────────────────────────
  { symbol: 'BRK-B', name: 'Berkshire Hathaway B',     exchange: 'NYSE',   currency: 'USD', sector: 'Finance' },
  { symbol: 'UNH',   name: 'UnitedHealth Group',        exchange: 'NYSE',   currency: 'USD', sector: 'Health' },
  { symbol: 'JNJ',   name: 'Johnson & Johnson',         exchange: 'NYSE',   currency: 'USD', sector: 'Health' },
  { symbol: 'XOM',   name: 'Exxon Mobil Corporation',  exchange: 'NYSE',   currency: 'USD', sector: 'Energy' },
  { symbol: 'JPM',   name: 'JPMorgan Chase & Co.',     exchange: 'NYSE',   currency: 'USD', sector: 'Finance' },
  { symbol: 'V',     name: 'Visa Inc.',                 exchange: 'NYSE',   currency: 'USD', sector: 'Finance' },
  { symbol: 'PG',    name: 'Procter & Gamble Co.',     exchange: 'NYSE',   currency: 'USD', sector: 'Consumer' },
  { symbol: 'MA',    name: 'Mastercard Inc.',           exchange: 'NYSE',   currency: 'USD', sector: 'Finance' },
  { symbol: 'HD',    name: 'The Home Depot Inc.',       exchange: 'NYSE',   currency: 'USD', sector: 'Retail' },
  { symbol: 'CVX',   name: 'Chevron Corporation',       exchange: 'NYSE',   currency: 'USD', sector: 'Energy' },
  { symbol: 'MRK',   name: 'Merck & Co. Inc.',         exchange: 'NYSE',   currency: 'USD', sector: 'Health' },
  { symbol: 'LLY',   name: 'Eli Lilly and Company',    exchange: 'NYSE',   currency: 'USD', sector: 'Health' },
  { symbol: 'PEP',   name: 'PepsiCo Inc.',              exchange: 'NYSE',   currency: 'USD', sector: 'Food' },
  { symbol: 'KO',    name: 'The Coca-Cola Company',    exchange: 'NYSE',   currency: 'USD', sector: 'Food' },
  { symbol: 'TMO',   name: 'Thermo Fisher Scientific', exchange: 'NYSE',   currency: 'USD', sector: 'Health' },
  { symbol: 'MCD',   name: "McDonald's Corporation",   exchange: 'NYSE',   currency: 'USD', sector: 'Food' },
  { symbol: 'WMT',   name: 'Walmart Inc.',              exchange: 'NYSE',   currency: 'USD', sector: 'Retail' },
  { symbol: 'BAC',   name: 'Bank of America Corp.',    exchange: 'NYSE',   currency: 'USD', sector: 'Finance' },
  { symbol: 'DIS',   name: 'The Walt Disney Company',  exchange: 'NYSE',   currency: 'USD', sector: 'Media' },
  { symbol: 'CRM',   name: 'Salesforce Inc.',           exchange: 'NYSE',   currency: 'USD', sector: 'Tech' },
  { symbol: 'WFC',   name: 'Wells Fargo & Company',    exchange: 'NYSE',   currency: 'USD', sector: 'Finance' },
  { symbol: 'GS',    name: 'The Goldman Sachs Group',  exchange: 'NYSE',   currency: 'USD', sector: 'Finance' },
  { symbol: 'MS',    name: 'Morgan Stanley',            exchange: 'NYSE',   currency: 'USD', sector: 'Finance' },
  { symbol: 'BA',    name: 'The Boeing Company',        exchange: 'NYSE',   currency: 'USD', sector: 'Industry' },
  { symbol: 'CAT',   name: 'Caterpillar Inc.',          exchange: 'NYSE',   currency: 'USD', sector: 'Industry' },
  { symbol: 'HON',   name: 'Honeywell International',  exchange: 'NYSE',   currency: 'USD', sector: 'Industry' },
  { symbol: 'RTX',   name: 'RTX Corporation',           exchange: 'NYSE',   currency: 'USD', sector: 'Defense' },
  { symbol: 'LMT',   name: 'Lockheed Martin Corp.',    exchange: 'NYSE',   currency: 'USD', sector: 'Defense' },
  { symbol: 'NEE',   name: 'NextEra Energy Inc.',       exchange: 'NYSE',   currency: 'USD', sector: 'Energy' },
  { symbol: 'ABT',   name: 'Abbott Laboratories',       exchange: 'NYSE',   currency: 'USD', sector: 'Health' },
  { symbol: 'PM',    name: 'Philip Morris International',exchange:'NYSE',   currency: 'USD', sector: 'Consumer' },
  { symbol: 'IBM',   name: 'IBM Corporation',           exchange: 'NYSE',   currency: 'USD', sector: 'Tech' },
  { symbol: 'GE',    name: 'GE Aerospace',              exchange: 'NYSE',   currency: 'USD', sector: 'Industry' },
  { symbol: 'SPY',   name: 'SPDR S&P 500 ETF',         exchange: 'NYSE',   currency: 'USD', sector: 'ETF' },
  { symbol: 'QQQ',   name: 'Invesco QQQ Trust',         exchange: 'NASDAQ', currency: 'USD', sector: 'ETF' },
  // ── CANADA TSX ───────────────────────────────────────────
  { symbol: 'RY.TO',    name: 'Royal Bank of Canada',   exchange: 'TSX', currency: 'CAD', sector: 'Finance' },
  { symbol: 'TD.TO',    name: 'Toronto-Dominion Bank',  exchange: 'TSX', currency: 'CAD', sector: 'Finance' },
  { symbol: 'BNS.TO',   name: 'Bank of Nova Scotia',    exchange: 'TSX', currency: 'CAD', sector: 'Finance' },
  { symbol: 'BMO.TO',   name: 'Bank of Montreal',       exchange: 'TSX', currency: 'CAD', sector: 'Finance' },
  { symbol: 'CM.TO',    name: 'CIBC',                   exchange: 'TSX', currency: 'CAD', sector: 'Finance' },
  { symbol: 'CNR.TO',   name: 'Canadian National Railway',exchange:'TSX', currency: 'CAD', sector: 'Industry' },
  { symbol: 'CP.TO',    name: 'Canadian Pacific Kansas City',exchange:'TSX',currency:'CAD',sector:'Industry' },
  { symbol: 'ENB.TO',   name: 'Enbridge Inc.',           exchange: 'TSX', currency: 'CAD', sector: 'Energy' },
  { symbol: 'TRP.TO',   name: 'TC Energy Corporation',  exchange: 'TSX', currency: 'CAD', sector: 'Energy' },
  { symbol: 'SU.TO',    name: 'Suncor Energy Inc.',      exchange: 'TSX', currency: 'CAD', sector: 'Energy' },
  { symbol: 'CNQ.TO',   name: 'Canadian Natural Resources',exchange:'TSX',currency:'CAD', sector: 'Energy' },
  { symbol: 'BCE.TO',   name: 'BCE Inc.',                exchange: 'TSX', currency: 'CAD', sector: 'Telecom' },
  { symbol: 'T.TO',     name: 'TELUS Corporation',       exchange: 'TSX', currency: 'CAD', sector: 'Telecom' },
  { symbol: 'SHOP.TO',  name: 'Shopify Inc.',            exchange: 'TSX', currency: 'CAD', sector: 'Tech' },
  { symbol: 'MFC.TO',   name: 'Manulife Financial',      exchange: 'TSX', currency: 'CAD', sector: 'Finance' },
  { symbol: 'SLF.TO',   name: 'Sun Life Financial',      exchange: 'TSX', currency: 'CAD', sector: 'Finance' },
  { symbol: 'BAM.TO',   name: 'Brookfield Asset Mgmt',  exchange: 'TSX', currency: 'CAD', sector: 'Finance' },
  { symbol: 'ABX.TO',   name: 'Barrick Gold Corp.',      exchange: 'TSX', currency: 'CAD', sector: 'Mining' },
  { symbol: 'NTR.TO',   name: 'Nutrien Ltd.',            exchange: 'TSX', currency: 'CAD', sector: 'Materials' },
  { symbol: 'ATD.TO',   name: 'Alimentation Couche-Tard',exchange:'TSX', currency: 'CAD', sector: 'Retail' },
  { symbol: 'L.TO',     name: 'Loblaw Companies Ltd',    exchange: 'TSX', currency: 'CAD', sector: 'Retail' },
  { symbol: 'MRU.TO',   name: 'Metro Inc.',              exchange: 'TSX', currency: 'CAD', sector: 'Retail' },
  { symbol: 'WN.TO',    name: 'George Weston Limited',   exchange: 'TSX', currency: 'CAD', sector: 'Retail' },
  { symbol: 'GWO.TO',   name: 'Great-West Lifeco',       exchange: 'TSX', currency: 'CAD', sector: 'Finance' },
  { symbol: 'POW.TO',   name: 'Power Corporation',       exchange: 'TSX', currency: 'CAD', sector: 'Finance' },
  { symbol: 'FFH.TO',   name: 'Fairfax Financial',       exchange: 'TSX', currency: 'CAD', sector: 'Finance' },
  { symbol: 'AEM.TO',   name: 'Agnico Eagle Mines',      exchange: 'TSX', currency: 'CAD', sector: 'Mining' },
  { symbol: 'WPM.TO',   name: 'Wheaton Precious Metals', exchange: 'TSX', currency: 'CAD', sector: 'Mining' },
  { symbol: 'IMO.TO',   name: 'Imperial Oil Ltd.',        exchange: 'TSX', currency: 'CAD', sector: 'Energy' },
  { symbol: 'CVE.TO',   name: 'Cenovus Energy Inc.',     exchange: 'TSX', currency: 'CAD', sector: 'Energy' },
];
